import { Component, OnInit } from '@angular/core';
import lgZoom from 'lightgallery/plugins/zoom';
import lgVideo from 'lightgallery/plugins/video';
import { BeforeSlideDetail } from 'lightgallery/lg-events';
@Component({
  selector: 'app-gallery',
  templateUrl: './gallery.component.html',
  styleUrls: ['./gallery.component.scss'],
})
export class GalleryComponent implements OnInit {
  settings = {
    counter: false,
    plugins: [lgVideo],
  };
  images: any = [

    'assets/gallery/wafi-lounge.mp4',
    'assets/gallery/images/wafi (1).jpg',
    'assets/gallery/images/wafi (2).jpg',
    'assets/gallery/images/wafi (3).jpg',
    'assets/gallery/images/wafi (4).jpg',
    'assets/gallery/images/wafi (5).jpg',
    'assets/gallery/images/wafi (6).jpg',
    'assets/gallery/images/wafi (7).jpg',
    'assets/gallery/images/wafi (8).jpg',
    'assets/gallery/images/wafi (9).jpg',
    'assets/gallery/images/wafi (10).jpg',
    'assets/gallery/images/wafi (11).jpg',
    'assets/gallery/images/wafi (12).jpg',
    'assets/gallery/images/wafi (13).jpg',
    'assets/gallery/images/wafi (14).jpg',
    'assets/gallery/images/wafi (15).jpg',
    'assets/gallery/images/wafi (16).jpg',
    'assets/gallery/images/wafi (17).jpg',
    'assets/gallery/images/wafi (18).jpg',
    'assets/gallery/images/wafi (19).jpg',
    'assets/gallery/images/wafi (20).jpg',
    'assets/gallery/images/wafi (21).jpg',
    'assets/gallery/images/wafi (22).jpg',
    'assets/gallery/images/wafi (23).jpg',
    'assets/gallery/images/wafi (24).jpg',
    'assets/gallery/images/wafi (25).jpg',
    'assets/gallery/images/wafi (26).jpg',
    'assets/gallery/images/wafi (27).jpg',
    'assets/gallery/images/wafi (28).jpg',
    'assets/gallery/images/wafi (29).jpg',
    'assets/gallery/images/wafi (30).jpg',
    'assets/gallery/images/wafi (31).jpg',
    'assets/gallery/images/wafi (32).jpg',
    'assets/gallery/images/wafi (33).jpg',
    'assets/gallery/images/wafi (34).jpg',
    'assets/gallery/images/wafi (35).jpg',
    'assets/gallery/images/wafi (36).jpg',
    'assets/gallery/images/wafi (37).jpg',
    'assets/gallery/images/wafi (38).jpg',
    'assets/gallery/images/wafi (39).jpg',
    'assets/gallery/images/wafi (40).jpg',
    'assets/gallery/images/wafi (41).jpg',
    'assets/gallery/images/wafi (42).jpg',
    'assets/gallery/images/wafi (43).jpg',
    'assets/gallery/images/wafi (44).jpg',
    'assets/gallery/images/wafi (45).jpg',
    'assets/gallery/images/wafi (46).jpg',
    'assets/gallery/images/wafi (47).jpg',
    'assets/gallery/images/wafi (48).jpg',
    'assets/gallery/images/wafi (49).jpg',
    'assets/gallery/images/wafi (50).jpg',
    'assets/gallery/images/wafi (51).jpg',
    'assets/gallery/images/wafi (52).jpg',
    'assets/gallery/images/wafi (53).jpg',
    'assets/gallery/images/wafi (54).jpg',
    'assets/gallery/images/wafi (55).jpg',
    'assets/gallery/images/wafi (56).jpg',
    'assets/gallery/images/wafi (57).jpg',
    'assets/gallery/images/wafi (58).jpg',
    'assets/gallery/images/wafi (59).jpg',
    'assets/gallery/images/wafi (60).jpg',
    'assets/gallery/images/wafi (61).jpg',
    'assets/gallery/images/wafi (62).jpg',
    'assets/gallery/images/wafi (63).jpg',
    'assets/gallery/images/wafi (64).jpg',
    'assets/gallery/images/wafi (65).jpg',
    'assets/gallery/images/wafi (66).jpg',
    'assets/gallery/images/wafi (67).jpg',
    'assets/gallery/images/wafi (68).jpg',
    'assets/gallery/images/wafi (69).jpg',
    'assets/gallery/images/wafi (70).jpg',
    'assets/gallery/images/wafi (71).jpg',
    'assets/gallery/images/wafi (72).jpg',
    'assets/gallery/images/wafi (73).jpg',
    'assets/gallery/images/wafi (74).jpg',
    'assets/gallery/images/wafi (75).jpg',
    'assets/gallery/images/wafi (76).jpg',
    'assets/gallery/images/wafi (77).jpg',
    'assets/gallery/images/wafi (78).jpg',
    'assets/gallery/images/wafi (79).jpg',
    'assets/gallery/images/wafi (80).jpg',
    'assets/gallery/images/wafi (81).jpg',
    'assets/gallery/images/wafi (82).jpg',
    'assets/gallery/images/wafi (83).jpg',
    'assets/gallery/images/wafi (84).jpg',
    'assets/gallery/images/wafi (85).jpg',
    'assets/gallery/images/wafi (86).jpg',
    'assets/gallery/images/wafi (87).jpg',
    'assets/gallery/images/wafi (88).jpg',
    'assets/gallery/images/wafi (89).jpg',
    'assets/gallery/images/wafi (90).jpg',
    'assets/gallery/images/wafi (91).jpg',
    'assets/gallery/images/wafi (92).jpg',
    'assets/gallery/images/wafi (93).jpg',
  ];
  onBeforeSlide = (detail: BeforeSlideDetail): void => {
    const { index, prevIndex } = detail;
  };
  constructor() {}

  ngOnInit(): void {}
}
